name: my-clock

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 一定要加的東西

      - name: docker build image
        run: docker build -t myclock:1.0 .
